platform :ios, '9.0'
use_frameworks!

def share_pods
   pod 'Masonry'
   pod 'SDWebImage'
   pod 'ReactiveCocoa', '2.3.1'
#   pod 'ZKUDID', '~> 2.0'
   pod 'AFNetworking', '~> 3.1.0'
end

target 'SK_UIKite' do
    share_pods
    pod 'TSMessages'
    pod 'LEETheme'  #主题颜色#
end
