platform :ios, '9.0'
use_frameworks!

def share_pods
   pod 'Masonry'
   pod 'SDWebImage'
   pod 'ReactiveCocoa', '2.3.1'
   pod 'AFNetworking', '~> 3.1.0'
#   pod 'ReactiveObjC', '~> 3.1.0'
end

target 'SK_UIKite' do
    share_pods
    pod 'TSMessages'
    pod 'LEETheme'  #主题颜色#
    pod 'SDWebImage/GIF' #GIF图#
    pod 'UINavigation-SXFixSpace' #导航栏两侧按钮间距
    pod 'SocketRocket'
    pod 'lottie-ios', '~> 2.5.2'
end

